### ISSUE TITLE
Choosing project on search bar does not filter appropriate deployments

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/arms-fims#13] opened 2016-09-05 19:44 UTC
When i choose a project on "Search"
http://arms.biocodellc.com/deployments/search
i get ALL the deployments from all projects.... should just show deployments for the selected project.

**Comment by rodney757** [comment] 2016-09-05 20:44
I'm not sure why this happens to you. I remember it happened a month or 2
ago as well. However I still can't reproduce the problem.

**Comment by rodney757** [comment] 2016-09-24 14:16
since we rewrote the search page to use angularjs, this should be fixed now

**Closed as completed by rodney757** 2016-09-24 14:16 UTC
